# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86a3347909ed5a103fc000a142956ae7bf643afd419f00955bed93118665d3e877b01c5f22ee36aed678126d52e09f0d8e8360fc03634a9f0b44f871e6985020

test:
  secret_key_base: e3fba88f297edc4c7cb62490d53444dc1f15581dadd1c69a01ceea2fc0f6ac966834da4a678a35f30b32fe64def994c7419fe2651e8ae93a4068c4d1b2ebdaba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
